// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: something_recorded.proto

package fixture

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SomethingRecorded is a sample event encoded with Protocol Buffers.
type SomethingRecorded struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What was recorded.
	What string `protobuf:"bytes,1,opt,name=what,proto3" json:"what,omitempty"`
	// When it was recorded. The field is not named occurred_on: the Go field it
	// generates would collide with the OccurredOn method an event needs.
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SomethingRecorded) Reset() {
	*x = SomethingRecorded{}
	mi := &file_something_recorded_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SomethingRecorded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomethingRecorded) ProtoMessage() {}

func (x *SomethingRecorded) ProtoReflect() protoreflect.Message {
	mi := &file_something_recorded_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SomethingRecorded.ProtoReflect.Descriptor instead.
func (*SomethingRecorded) Descriptor() ([]byte, []int) {
	return file_something_recorded_proto_rawDescGZIP(), []int{0}
}

func (x *SomethingRecorded) GetWhat() string {
	if x != nil {
		return x.What
	}
	return ""
}

func (x *SomethingRecorded) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_something_recorded_proto protoreflect.FileDescriptor

const file_something_recorded_proto_rawDesc = "" +
	"\n" +
	"\x18something_recorded.proto\x12\x10eventide.fixture\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n" +
	"\x11SomethingRecorded\x12\x12\n" +
	"\x04what\x18\x01 \x01(\tR\x04what\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAtB2Z0github.com/grandper/go-eventide/internal/fixtureb\x06proto3"

var (
	file_something_recorded_proto_rawDescOnce sync.Once
	file_something_recorded_proto_rawDescData []byte
)

func file_something_recorded_proto_rawDescGZIP() []byte {
	file_something_recorded_proto_rawDescOnce.Do(func() {
		file_something_recorded_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_something_recorded_proto_rawDesc), len(file_something_recorded_proto_rawDesc)))
	})
	return file_something_recorded_proto_rawDescData
}

var file_something_recorded_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_something_recorded_proto_goTypes = []any{
	(*SomethingRecorded)(nil),     // 0: eventide.fixture.SomethingRecorded
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_something_recorded_proto_depIdxs = []int32{
	1, // 0: eventide.fixture.SomethingRecorded.occurred_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_something_recorded_proto_init() }
func file_something_recorded_proto_init() {
	if File_something_recorded_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_something_recorded_proto_rawDesc), len(file_something_recorded_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_something_recorded_proto_goTypes,
		DependencyIndexes: file_something_recorded_proto_depIdxs,
		MessageInfos:      file_something_recorded_proto_msgTypes,
	}.Build()
	File_something_recorded_proto = out.File
	file_something_recorded_proto_goTypes = nil
	file_something_recorded_proto_depIdxs = nil
}
